### ISSUE TITLE
震惊

### ISSUE THREAD

**Issue by KiteAB** [TravinDreek/travindreek.github.io#1]
我们的年轻小伙爬咳嗽终于有博客了！

**Comment by TravinDreek** [comment]
其实早就有了, 但是很久都没有更新和维护过, 所以就把它关了. 这次打算重新把它开好, 顺便翻新一下.

**Comment by KiteAB** [comment]
行吧   其实我最近也是这样的23333    你这是基于什么框架

**Comment by TravinDreek** [comment]
加了各种插件的docsify. 不过现在还有些bug没修.

**Comment by KiteAB** [comment]
彳亍口巴     https://kiteab.github.io/

**Comment by KiteAB** [comment]
xdddd 变相推荐一波

**Comment by KiteAB** [comment]
emm

**Comment by KiteAB** [comment]
del算了吧   就随便聊聊而已

**Comment by TravinDreek** [comment]
女子
